/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inerfaces;

import Funciones.Encriptar;
import javax.swing.JOptionPane;

/**
 *
 * @author Adolfo
 */
public class Interfaz2 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz2
     */
    public Interfaz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Texto = new javax.swing.JTextField();
        Clave = new javax.swing.JTextField();
        Encriptar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TextoEncriptado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encriptación MAC ");
        setBackground(new java.awt.Color(0, 0, 102));
        setMinimumSize(new java.awt.Dimension(490, 306));
        setPreferredSize(new java.awt.Dimension(490, 306));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Encriptación MAC");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 0, 206, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Texto a encriptar (16 Letras)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 90, 248, 22);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Clave (16 Letras)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 145, 22);

        Texto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoActionPerformed(evt);
            }
        });
        getContentPane().add(Texto);
        Texto.setBounds(270, 80, 220, 30);

        Clave.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaveActionPerformed(evt);
            }
        });
        getContentPane().add(Clave);
        Clave.setBounds(270, 140, 220, 30);

        Encriptar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Encriptar.setText("Encriptar");
        Encriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncriptarActionPerformed(evt);
            }
        });
        getContentPane().add(Encriptar);
        Encriptar.setBounds(40, 240, 121, 30);

        Regresar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar);
        Regresar.setBounds(350, 240, 119, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Texto Encriptado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 200, 148, 22);

        TextoEncriptado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(TextoEncriptado);
        TextoEncriptado.setBounds(270, 190, 220, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 0, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoActionPerformed

    private void ClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClaveActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        Interfaz1 I = new Interfaz1();
        I.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void EncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncriptarActionPerformed
        // TODO add your handling code here:
        Validar();
    }//GEN-LAST:event_EncriptarActionPerformed

    private void Validar()
    {
        if(Texto.getText().length()!=16 || Clave.getText().length()!=16)
        {
            JOptionPane.showMessageDialog(null, "Debe tener 16 caracteres el texto y la clave", "Importante", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            Encriptar E=new Encriptar();
            String Text = Texto.getText();
            String Clav = Clave.getText();
            E.SeparaLetras(Text, Clav);
            String Encrip=E.Terminado();
            TextoEncriptado.setText(Encrip);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Clave;
    private javax.swing.JButton Encriptar;
    private javax.swing.JButton Regresar;
    private javax.swing.JTextField Texto;
    private javax.swing.JTextField TextoEncriptado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
